### PR TITLE
No more be-ing

### PR DESCRIPTION
**Pull request by Khhs167**

### CODE REVIEW

**Comment by Khhs167** [comment]
ReCT has this massive flaw

**Comment by RedCubeDev-ByteSpace** [comment]
nah fam

**Comment by Khhs167** [comment]
Things might be, and that shouldnt be allowed

**Comment by RedCubeDev-ByteSpace** [comment]
no >:(

**Comment by Khhs167** [comment]
yes >:(

**Comment by Khhs167** [comment]
ok i'll close but keep the branch
ok?

**Pull request closed without merging**
