### PR TITLE
Added space that was missing

### PR DESCRIPTION
**Pull request by WillTheDeveloper**

### CODE REVIEW

**Comment by tokorv** [comment]
Didn’t exactly contribute a lot, gonna rework cli anyway.

**Comment by mauro-balades** [comment]
Bro, you can still have the pull request up...

**Comment by WillTheDeveloper** [comment]
I think this should still get merged. Once someone else notices it then they will do the same.

**Comment by tokorv** [comment]
Reopening

**Comment by WillTheDeveloper** [comment]
Could someone look at merging this or something because I am unable to update my fork until this is sorted :)

**Comment by tokorv** [comment]
This branch now has conflicts with the new cli implementation... Is there I can do to let you update your fork? @WillTheDeveloper

**Comment by tokorv** [comment]
Spoke with Will, gonna close pull request.

**Comment by mauro-balades** [comment]
Let me do a fork...

**Pull request closed without merging**
