### PR TITLE
added CPP linking

### PR DESCRIPTION
**Pull request by mauro-balades**

### CODE REVIEW

**Comment by mauro-balades** [comment]
You should really do all of this process inside rgoc itself. If you want this project to grow, you should embed everything into a single executable instead of the user needing to execute a shell script.

**Review by Khhs167 — APPROVED** [review]
Well i'd approve this

**Comment by RedCubeDev-ByteSpace** [comment]
Yeah I'm aware of that, tho it will always require at least the LLVM toolchain, but so does Clang so i feel like that shouldn't be an issue. Currently Rgoc is just using Clang because it works for now :+1: 
But the end goal is definitely to make it completely independent from clang, just didn't get to doing that yet.

Tho I feel like including the entire c++ stdlib when linking is kind of extreme haha. Unless it's optimized away when unused?

**Comment by RedCubeDev-ByteSpace** [comment]
Also the user doens't need to run a shell script :flushed:

**Comment by mauro-balades** [comment]
> Yeah I'm aware of that, tho it will always require at least the LLVM toolchain, but so does Clang so i feel like that shouldn't be an issue. Currently Rgoc is just using Clang because it works for now :+1: 
> But the end goal is definitely to make it completely independent from clang, just didn't get to doing that yet.
> 
> Tho I feel like including the entire c++ stdlib when linking is kind of extreme haha. Unless it's optimized away when unused?

Linking the CPP stdlib shouldn't be any problem since it will only appear symbols you use, and those symbols sometimes will not even be ever used if the user does not install a CPP package

**Comment by mauro-balades** [comment]
> Also the user doens't need to run a shell script :flushed:  

What do you mean?

**Comment by RedCubeDev-ByteSpace** [comment]
> What do you mean?

Well what shell script were you referring to in your first Message?

**Comment by mauro-balades** [comment]
>
> > What do you mean?
> 
> Well what shell script were you referring to in your first Message?

https://github.com/ReCT-Lang/ReCT-Go-Compiler/blob/main/link_lin.sh
https://github.com/ReCT-Lang/ReCT-Go-Compiler/blob/main/run_lin.sh

and all of the *.ll outputs and test files that should really be ignored by git

**Comment by RedCubeDev-ByteSpace** [comment]
Oh those two are no longer needed. I guess you're right, I got some cleaning todo haha

**Comment by RedCubeDev-ByteSpace** [comment]
Just noticed that this change wouldn't actually help as, like I said, that shell script isn't used anymore.
Those things are now handled by rgoc itself, will add asap.

**Comment by mauro-balades** [comment]
~~but use it for our cpp package ;)~~

**Pull request closed without merging**
